# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c1a421ccb666e4a78c7daf53728df2b21bf935436e2dfd324d82afe1331bce0bf5ac6d86b2fe88c871bb8353d3e1a0949011ca6a04ba5977aaeea015cb9f3708

test:
  secret_key_base: ba0d9a46b1a6e1f4d71aaa3b4621787fa4f81afc5a15a6983eb633225a2c59be6c7156335be87082b13998cc35615a7c2d7e2d54a7819596a1280c42b39d07db

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
